In [1]:
import pandas as pd 
from datetime import datetime


df= pd.read_csv('dataELO.csv')
df.tail(20)

,Comp,Temp,Data,Casa,GC,GF,Fora,Res,PC,PF,J
17672,Série A,2023,2023-07-29,Atlético-MG,1,2,Flamengo,VV,0,3,162
17673,Série A,2023,2023-07-29,Corinthians,3,1,Vasco,VC,3,0,161
17674,Série A,2023,2023-07-29,Fluminense,1,0,Santos,VC,3,0,160
17675,Série A,2023,2023-07-30,Botafogo,4,1,Coritiba,VC,3,0,167
17676,Série B,2023,2023-07-30,Tombense,2,2,Criciúma,E,1,1,198
17677,Série A,2023,2023-07-30,América-MG,1,4,Palmeiras,VV,0,3,166
17678,Série B,2023,2023-07-30,Ponte Preta,2,2,Vitória,E,1,1,196
17679,Série B,2023,2023-07-30,Novorizontino,3,1,Vila Nova-GO,VC,3,0,197
17680,Série A,2023,2023-07-30,São Paulo,0,0,Bahia,E,1,1,165
17681,Série A,2023,2023-07-30,Goiás,1,1,Grêmio,E,1,1,168
17682,Série B,2023,2023-08-01,Mirassol,2,2,Avaí,E,1,1,199
17683,Série B,2023,2023-08-01,Sampaio Corrêa,0,0,Botafogo-SP,E,1,1,200
17684,Série B,2023,2023-08-01,CRB,2,1,Atlético-GO,VC,3,0,201
17685,Série B,2023,2023-08-02,Vitória,2,0,ABC,VC,3,0,202
17686,Série B,2023,2023-08-02,Ituano,1,0,Tombense,VC,3,0,203
17687,Série B,2023,2023-08-02,Juventude,1,0,Novorizontino,VC,3,0,204
17688,Série B,2023,2023-08-02,Vila Nova-GO,0,1,Sport,VV,0,3,205
17689,Série B,2023,2023-08-02,Guarani,0,0,Ceará,E,1,1,206
17690,Série B,2023,2023-08-02,Londrina,1,1,Chapecoense,E,1,1,208
17691,Série B,2023,2023-08-02,Criciúma,2,1,Ponte Preta,VC,3,0,207

In [3]:
#This function updates the Elo ratings and creates a ranking

timestamp_df = pd.DataFrame(columns=['Timestamp'])
def update_elo(df):
    #Gives different weights to each competition
    k_factor_map = {
                    'Mineiro': 10,
                    'Série C': 10, 
                    'Série B': 15, 
                    'Carioca': 15, 
                    'Paulista': 20, 
                    'CBR': 30, 
                    'Série A': 40,
                    'Libertadores': 50}
    teams = {}
    elo_ranking = {}
    average_elo = {}
    team_games = {}
    team_victories = {}
    team_losses = {}
    team_goals = {}
    team_draws = {}
    
    #Creates a list of teams and gives then an initial rating of 1500
    for index, row in df.iterrows():
        home_team, away_team = row['Casa'], row['Fora']
        comp_level = row['Comp']
        k_factor = k_factor_map.get(comp_level, 50) 
        if home_team not in teams:
            teams[home_team] = 1500
            elo_ranking[home_team] = teams[home_team]
        if away_team not in teams:
            teams[away_team] = 1500
            elo_ranking[away_team] = teams[away_team]
        home_elo, away_elo = teams[home_team], teams[away_team]
        home_score, away_score = row['GC'], row['GF']
        result = row['Res']
        #Gives different weights for home and away games
        if result == 'VC':
            home_result, away_result = 1, 0
        elif result == 'VV':
            home_result, away_result = 0, 1
        else:
            home_result, away_result = 0.5, 0.5
        home_expected = 1 / (1 + 10 ** ((away_elo - home_elo - 100) / 400))
        away_expected = 1 / (1 + 10 ** ((home_elo - away_elo + 100) / 400))
        
        #Calculates the number of goals
        if home_team in team_goals:
            team_goals[home_team] += home_score
        else:
            team_goals[home_team] = home_score

        if away_team in team_goals:
            team_goals[away_team] += away_score
        else:
            team_goals[away_team] = away_score
       # Update the number of victories, losses, and draws for each team
        if result == 'VC':
            home_result, away_result = 1, 0
            if home_team in team_victories:
                team_victories[home_team] += 1
            else:
                team_victories[home_team] = 1
            if away_team in team_losses:
                team_losses[away_team] += 1
            else:
                team_losses[away_team] = 1
        elif result == 'VV':
            home_result, away_result = 0, 1
            if home_team in team_losses:
                team_losses[home_team] += 1
            else:
                team_losses[home_team] = 1
            if away_team in team_victories:
                team_victories[away_team] += 1
            else:
                team_victories[away_team] = 1
        else:
            home_result, away_result = 0.5, 0.5
            if home_team in team_draws:
                team_draws[home_team] += 1
            else:
                team_draws[home_team] = 1
            if away_team in team_draws:
                team_draws[away_team] += 1
            else:
                team_draws[away_team] = 1
        # Update the number of games played for each team
        if home_team in team_games:
            team_games[home_team] += 1
        else:
            team_games[home_team] = 1
        if away_team in team_games:
            team_games[away_team] += 1
        else:
            team_games[away_team] = 1
        
        # Calculate the goal difference and adjust the K factor accordingly
        goal_diff = abs(home_score - away_score)
        if goal_diff >= 4:
            k_factor = k_factor + 0.75 + (goal_diff - 4) / 8
        elif goal_diff == 3:
            k_factor = k_factor + 0.75
        elif goal_diff == 2:
            k_factor = k_factor + 0.5
        else:
            k_factor = k_factor
            
        # Calculate the rating difference factor
        rating_diff = abs(home_elo - away_elo)
        if rating_diff > 400:
            rating_diff = 400
        rating_factor = rating_diff / 400 + 1
            
        teams[home_team] = home_elo + rating_factor * k_factor * (home_result - home_expected)
        teams[away_team] = away_elo + rating_factor * k_factor * (away_result - away_expected)
        teams[home_team] = round(teams[home_team], 2)
        teams[away_team] = round(teams[away_team], 2)
        elo_ranking[home_team] = teams[home_team]
        elo_ranking[away_team] = teams[away_team]
        df.at[index, 'Home_Elo'] = home_elo
        df.at[index, 'Away_Elo'] = away_elo
        df.at[index, 'Home_New_Elo'] = teams[home_team]
        df.at[index, 'Away_New_Elo'] = teams[away_team]

        
        for team, elo in teams.items():
            if team in average_elo:
                average_elo[team].append(elo)
            else:
                average_elo[team] = [elo]

    # Compute average Elo for each team
    for team, elo_list in average_elo.items():
        average_elo[team] = round(sum(elo_list) / len(elo_list), 2)

    #Createa the Datasets
    elo_df = pd.DataFrame.from_dict(elo_ranking, orient='index', columns=['Elo'])
    elo_df = elo_df.sort_values(by='Elo', ascending=False)
    elo_df.index.name = 'Time'
    elo_df.reset_index(inplace=True)
    elo_df = elo_df[~elo_df['Time'].str.contains(r'\(ARG\)|\(BOL\)|\(CHI\)|\(COL\)|\(EQU\)|\(MEX\)|\(PAR\)|\(PER\)|\(URU\)|\(VEN\)', regex=True)]
    elo_df['Jogos'] = elo_df['Time'].map(team_games) 
    elo_df = elo_df[elo_df['Jogos'] >= 30]
    elo_df['Rank'] = elo_df['Elo'].rank(ascending=False, method='dense')
    elo_df['Média'] = elo_df['Time'].map(average_elo).round(2)
    elo_df['#'] = elo_df['Média'].rank(ascending=False, method='dense')
    elo_df['Gols'] = elo_df['Time'].map(team_goals)
    elo_df['Vitórias'] = elo_df['Time'].map(team_victories)
    elo_df['Derrotas'] = elo_df['Time'].map(team_losses)
    elo_df['Empates'] = elo_df['Time'].map(team_draws)
    timestamp_now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    timestamp_df.loc[len(timestamp_df)] = [timestamp_now]

    
    return df, elo_df

df, elo_df = update_elo(df)
df.to_csv('dataELO.csv', index=False)
elo_df.to_json('dataELOranking.json', orient='records')
timestamp_df.to_json('timestamps.json')

In [4]:
elo_df.head(20)

,Time,Elo,Jogos,Rank,Média,#,Gols,Vitórias,Derrotas,Empates
0,Botafogo,1926.70,854,1.0,1657.22,12.0,1161,342,287,225
1,Flamengo,1892.95,880,2.0,1732.30,2.0,1301,407,240,233
2,Palmeiras,1861.86,845,3.0,1727.54,3.0,1303,404,230,211
3,Fluminense,1801.20,875,4.0,1691.05,10.0,1224,360,291,224
4,Red Bull Bragantino,1792.41,545,5.0,1572.20,26.0,712,206,204,135
5,Corinthians,1782.17,857,6.0,1715.32,5.0,1147,373,243,241
6,São Paulo,1778.23,830,7.0,1734.81,1.0,1201,375,227,228
7,Grêmio,1776.35,845,8.0,1717.74,4.0,1173,387,240,218
8,Cuiabá,1773.34,203,9.0,1499.20,46.0,199,63,72,68
9,Internacional,1772.13,839,10.0,1711.91,6.0,1144,379,245,215
10,Fortaleza,1757.91,566,11.0,1565.71,27.0,745,212,217,137
11,Athletico-PR,1748.29,862,12.0,1675.20,11.0,1141,345,306,211
12,Atlético-MG,1721.63,868,13.0,1708.16,7.0,1329,385,271,212
13,Bahia,1686.94,777,14.0,1600.41,18.0,961,276,280,221
14,Sport,1679.19,816,15.0,1615.25,16.0,1040,306,300,210
15,Cruzeiro,1672.96,863,16.0,1695.50,9.0,1276,390,262,211
16,América-MG,1671.69,591,17.0,1578.11,23.0,728,227,198,166
17,Coritiba,1671.64,849,18.0,1626.22,14.0,1084,321,314,214
18,Goiás,1660.43,843,19.0,1625.43,15.0,1146,324,314,205
19,Santos,1660.16,854,20.0,1707.90,8.0,1251,366,264,224

In [4]:
elo_df.to_json('dataELOranking.json', orient='records')

In [18]:
timestamp_df

             Timestamp
0  2023-07-21 14:49:30

In [10]:
df

,Comp,Temp,Data,Casa,GC,GF,Fora,Res,PC,PF,J,Home_Elo,Away_Elo,Home_New_Elo,Away_New_Elo
0,CBR,2003.0,2003-02-05,Bangu,2,1,Gama,VC,3,0,12.0,1500.0,1500.0,1511.0,1489.0
1,CBR,2003.0,2003-02-05,Pelotas,1,2,Guarani,VV,0,3,10.0,1500.0,1500.0,1481.0,1519.0
2,CBR,2003.0,2003-02-05,Botafogo-PB,1,4,Flamengo,VV,0,3,7.0,1500.0,1500.0,1480.0,1520.0
3,CBR,2003.0,2003-02-05,CFZ-DF,0,0,Fortaleza,E,1,1,11.0,1500.0,1500.0,1496.0,1504.0
4,CBR,2003.0,2003-02-05,CRB,0,1,Atlético-MG,VV,0,3,3.0,1500.0,1500.0,1481.0,1519.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10557,Série B,2023.0,2023-07-02,Ponte Preta,1,0,Novorizontino,VC,3,0,145.0,1561.0,1551.0,1566.0,1546.0
10558,Série A,2023.0,2023-07-03,Goiás,1,2,Coritiba,VV,0,3,130.0,1646.0,1535.0,1607.0,1574.0
10559,Série B,2023.0,2023-07-03,Mirassol,0,1,Ituano,VV,0,3,148.0,1540.0,1517.0,1529.0,1528.0
10560,Série B,2023.0,2023-07-03,Botafogo-SP,1,0,Guarani,VC,3,0,149.0,1519.0,1584.0,1527.0,1576.0
10561,Série B,2023.0,2023-07-05,CRB,2,0,Sport,VC,3,0,150.0,1607.0,1711.0,1617.0,1701.0

In [228]:
unique_values = df['Fora','Casa'].unique()
unique_values_sorted = sorted(unique_values)
print(unique_values_sorted)

['ABC', 'ASA', 'Alianza Lima (PER)', 'Altos', 'Always Ready (BOL)', 'America-RJ', 'Americano-RJ', 'América (COL)', 'América (MEX)', 'América (Teófilo Otoni)', 'América-MG', 'América-RN', 'América-SP', 'Anapolina', 'Aparecidense', 'Araxá', 'Argentinos Jrs (ARG)', 'Arsenal (ARG)', 'Athletic', 'Athletico-PR', 'Atlas', 'Atlético Acreano', 'Atlético Cearense', 'Atlético Nacional (COL)', 'Atlético PR', 'Atlético Sorocaba', 'Atlético Tucumán (COL)', 'Atlético-GO', 'Atlético-MG', 'Aucas (EQU)', 'Audax-RJ', 'Avaí', 'Bahia', 'Bangu', 'Baraúnas', 'Barcelona (EQU)', 'Barra Mansa', 'Barras', 'Barueri', 'Betim', 'Binacional', 'Boa', 'Boavista', 'Boca Juniors (ARG)', 'Bolívar (BOL)', 'Bonsucesso', 'Botafogo', 'Botafogo-PB', 'Botafogo-SP', 'Bragantino', 'Brasil de Pelotas', 'Brasil-RS', 'Brasiliense', 'Brusque', 'CRAC', 'CRB', 'CSA', 'Cabofriense', 'Caldense', 'Campinense', 'Capivariano', 'Caracas (VEN)', 'Cardoso Moreira', 'Catanduvense', 'Caxias', 'Ceará', 'Ceilândia', 'Central (ARG)', 'Cerro Porteño (PAR)', 'Chapecoense', 'Chivas (MEX)', 'Cobresal (CHI)', 'Coimbra', 'Colo Colo (CHI)', 'Colón', 'Comercial-SP', 'Confiança', 'Corinthians', 'Corinthians AL', 'Coritiba', 'Criciúma', 'Cruz Azul (MEX)', 'Cruzeiro', 'Cuiabá', 'Cúcuta (COL)', 'Danubio (URU)', 'Def. y Jus. (ARG)', 'Defensor (URU)', 'Del Valle (EQU)', 'Delfín (URU)', 'Democrata (Gov. Valadares)', 'Democrata (Sete Lagoas)', 'Dep. Anzoátegui', 'Dep. Cali (COL)', 'Dep. Lara (VEN)', 'Dep. Pereira (COL)', 'Dep. Quito (EQU)', 'Deportes Iquique (PER)', 'Duque de Caxias', 'Emelec (EQU)', 'Estudiantes (ARG)', 'Estudiantes (VEN)', 'Ferroviária', 'Ferroviário', 'Ferroviário CE', 'Ferroviário-CE', 'Figueirense', 'Flamengo', 'Floresta', 'Fluminense', 'Fortaleza', 'Friburguense', 'Funorte', 'G. Barueri/Prudente', 'Gama', 'Globo', 'Godoy Cruz (ARG)', 'Goiás', 'Grêmio', 'Guarani', 'Guarani-MG', 'Guarany-S', 'Guaraní (PAR)', 'Guaratinguetá', 'Huachipato (CHI)', 'Huracán (ARG)', 'ICASA', 'Icasa', 'Iguatu', 'Imperatriz', 'Ind. Medellín (COL)', 'Independiente (ARG)', 'Independiente Petrolero', 'Inter de Limeira', 'Internacional', 'Ipatinga', 'Ituano', 'Ituiutaba', 'Jacuipense', 'Joinville', 'Jorge Wilstermann (BOL)', 'Jr. Barranquilla (COL)', 'Juagares (MEX)', 'Juan Aurich (PER)', 'Juazeirense', 'Juventude', 'Juventus', 'LDU Quito (EQU)', 'La Calera (CHI)', 'La Guaira (VEN)', 'Lanús (ARG)', 'León (MEX)', 'Libertad (PAR)', 'Linense', 'Liverpool (URU)', 'Londrina', 'Luverdense', 'Macaé', 'Madureira', 'Mamoré', 'Manaus', 'Marcílio Dias', 'Maringá  .', 'Marília', 'Melgar (PER)', 'Mesquita', 'Metropolitanos (VEN)', 'Millonarios (COL)', 'Minas', 'Mineros de Guayana (VEN)', 'Mirassol', 'Mogi Mirim', 'Monagas', 'Monaguas (VEN)', 'Monte Azul', 'Montevidéo Wanderers (URU)', 'Moto Club', 'Mutum', 'Nacional (PAR)', 'Nacional (URU)', 'Nacional AM', 'Nacional-MG', 'Nacional-PB', "Newell's (ARG)", 'Noroeste', 'Nova Iguaçu', 'Novorizontino', 'Náutico', "O'Higgins (CHI)", 'Oeste', 'Olaria', 'Olimpia (PAR)', 'Olímpia', 'Once Caldas (COL)', 'Operário-MS', 'Operário-PR', 'Opérario-PR', 'Oriente Petrolero', 'Osasco Audax', 'PR - Atlético-MG', 'PR - Libertad', 'Palestino (CHI)', 'Palmeiras', 'Paraná', 'Patrocinense', 'Patronato (ARG)', 'Paulista', 'Paysandu', 'Penapolense', 'Peñarol (URU)', 'Ponte Preta', 'Portuguesa', 'Portuguesa RJ', 'Portuguesa Santista', 'Portuguesa-RJ', 'Pouso Alegre', 'Puebla', 'Pumas (MEX)', 'Quissamã', 'Racing (ARG)', 'Real Garcilaso (PER)', 'Red Bull', 'Red Bull Bragantino', 'Remo', 'Rentistas (URU)', 'Resende', 'Retrô', 'Rio Branco-AC', 'Rio Branco-MG', 'Rio Branco-SP', 'Rio Claro-SP', 'Rio Preto-SP', 'River Plate (ARG)', 'River Plate (URU)', 'Ríver', 'Salgueiro', 'Sampaio Corrêa', 'San José (BOL)', 'San Lorenzo (ARG)', 'Santa Cruz', 'Santa Fé (COL)', 'Santo André', 'Santos', 'Santos Laguna (BMEX)', 'Sertãozinho', 'Social', 'Sport', 'Sport Boys (BOL)', 'Sporting Cristal (PER)', 'São Bento', 'São Bernardo', 'São Caetano', 'São José-RS', 'São Luiz', 'São Paulo', 'São Raimundo', 'Talleres (ARG)', 'The Strongest (BOL)', 'Tigres (ARG)', 'Tigres (MEX)', 'Tigres do Brasil', 'Tijuana (MEX)', 'Tocantinópolis', 'Tolima (COL)', 'Toluca (MEX)', 'Tombense', 'Treze', 'Tricordiano', 'Trujillanos (MEX)', 'Tupi', 'Tupynambás', 'Táchira', 'U. Católica (CHI)', 'U. de Chile (CHI)', 'U. de Concepción (CHI)', 'URT', 'Uberaba', 'Uberlândia', 'Union Española', 'Universidad César Vallejo', 'Universitário (BOL)', 'Universitário (PER)', 'União Barbarense', 'União São João', 'Vasco', 'Vasco da Gama .', 'Vila Nova', 'Vila Nova-GO', 'Villa Nova-MG', 'Vitória', 'Volta Redonda', 'Vélez (ARG)', 'XV de Piracicaba', 'Ypiranga-RS', 'Zamora (VEN)', 'Zulia (VEN)', 'Água Santa', 'Águia de Marabá', 'Ñublense (CHI)']

In [230]:
df['Temp'] = df['Temp'].astype(str)
df

,Comp,Temp,Data,Casa,GC,GF,Fora,Res,PC,PF,J,Home_Elo,Away_Elo,Home_New_Elo,Away_New_Elo
0,Paulista,2003.0,2003-01-25,Marília,0,2,Corinthians,VV,0,3,2,1500.0,1500.0,1487.0,1513.0
1,Paulista,2003.0,2003-01-26,União São João,0,2,América-SP,VV,0,3,9,1500.0,1500.0,1487.0,1513.0
2,Paulista,2003.0,2003-01-26,Portuguesa,0,3,São Caetano,VV,0,3,8,1500.0,1500.0,1487.0,1513.0
3,Paulista,2003.0,2003-01-26,Paulista,2,1,São Paulo,VC,3,0,7,1500.0,1500.0,1507.0,1493.0
4,Paulista,2003.0,2003-01-26,Guarani,4,0,União Barbarense,VC,3,0,3,1500.0,1500.0,1507.0,1493.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16694,Série A,2023.0,2023-06-25,Palmeiras,0,1,Botafogo,VV,0,3,116,1809.0,1768.0,1778.0,1799.0
16695,Série A,2023.0,2023-06-25,Red Bull Bragantino,2,0,Goiás,VC,3,0,118,1683.0,1596.0,1696.0,1583.0
16696,Série A,2023.0,2023-06-25,Grêmio,5,1,Coritiba,VC,3,0,119,1759.0,1480.0,1766.0,1473.0
16697,Série A,2023.0,2023-06-25,Santos,2,3,Flamengo,VV,0,3,117,1621.0,1712.0,1596.0,1737.0
16698,Série A,2023.0,2023-06-26,Vasco,1,0,Cuiabá,VC,3,0,120,1523.0,1573.0,1542.0,1554.0

In [2]:
filt = (df['Casa'] == 'Corinthians') | (df['Fora'] == 'Corinthians')
df.loc[filt].tail(31)

,Comp,Temp,Data,Casa,GC,GF,Fora,Res,PC,PF,J
17107,CBR,2022,2022-10-19,Flamengo,1,1,Corinthians,E,1,1,121
17119,Série A,2022,2022-10-22,Santos,0,1,Corinthians,VV,0,3,324
17134,Série A,2022,2022-10-26,Corinthians,0,2,Fluminense,VV,0,3,333
17147,Série A,2022,2022-10-29,Goiás,0,0,Corinthians,E,1,1,341
17153,Série A,2022,2022-11-02,Flamengo,1,2,Corinthians,VV,0,3,346
17165,Série A,2022,2022-11-05,Corinthians,1,0,Ceará,VC,3,0,354
17184,Série A,2022,2022-11-09,Coritiba,2,2,Corinthians,E,1,1,369
17192,Série A,2022,2022-11-13,Corinthians,0,1,Atlético-MG,VV,0,3,375
17263,CBR,2023,2023-04-12,Remo,2,0,Corinthians,VC,3,0,68
17291,Série A,2023,2023-04-16,Corinthians,2,1,Cruzeiro,VC,3,0,9
17308,Série A,2023,2023-04-23,Goiás,3,1,Corinthians,VC,3,0,18
17318,CBR,2023,2023-04-26,Corinthians,2,0,Remo,VC,3,0,85
17338,Série A,2023,2023-04-29,Palmeiras,2,1,Corinthians,VC,3,0,24
17375,Série A,2023,2023-05-08,Corinthians,1,1,Fortaleza,E,1,1,40
17385,Série A,2023,2023-05-11,Botafogo,3,0,Corinthians,VC,3,0,48
17401,Série A,2023,2023-05-14,Corinthians,1,1,São Paulo,E,1,1,59
17409,CBR,2023,2023-05-17,Atlético-MG,2,0,Corinthians,VC,3,0,94
17430,Série A,2023,2023-05-21,Flamengo,1,0,Corinthians,VC,3,0,68
17456,Série A,2023,2023-05-28,Corinthians,2,0,Fluminense,VC,3,0,77
17468,CBR,2023,2023-05-31,Corinthians,2,0,Atlético-MG,VC,3,0,106
17482,Série A,2023,2023-06-03,América-MG,2,0,Corinthians,VC,3,0,81
17507,Série A,2023,2023-06-10,Corinthians,1,1,Cuiabá,E,1,1,91
17527,Série A,2023,2023-06-21,Santos,0,2,Corinthians,VV,0,3,102
17540,Série A,2023,2023-06-24,Athletico-PR,1,0,Corinthians,VC,3,0,113
17578,Série A,2023,2023-07-02,Corinthians,0,1,Red Bull Bragantino,VV,0,3,127
17589,CBR,2023,2023-07-05,América-MG,1,0,Corinthians,VC,3,0,111
17598,Série A,2023,2023-07-08,Atlético-MG,0,1,Corinthians,VV,0,3,134
17620,CBR,2023,2023-07-15,Corinthians,3,2,América-MG,VC,3,0,116
17643,Série A,2023,2023-07-22,Bahia,0,0,Corinthians,E,1,1,151
17660,CBR,2023,2023-07-25,Corinthians,2,1,São Paulo,VC,3,0,117
17673,Série A,2023,2023-07-29,Corinthians,3,1,Vasco,VC,3,0,161

In [35]:
filt = ((df['Casa'] == 'Corinthians') | (df['Fora'] == 'Corinthians'))
df.loc[filt].tail(30)

,Comp,Temp,Data,Casa,GC,GF,Fora,Res,PC,PF,J,Home_Elo,Away_Elo,Home_New_Elo,Away_New_Elo
17074,Série A,2022,2022-10-08,Corinthians,2,1,Athletico-PR,VC,3,0,301,1798.90,1774.67,1812.83,1760.74
17087,CBR,2022,2022-10-12,Corinthians,0,0,Flamengo,E,1,1,120,1812.83,1879.64,1811.16,1881.31
17107,CBR,2022,2022-10-19,Flamengo,1,1,Corinthians,E,1,1,121,1893.26,1811.16,1884.57,1819.85
17119,Série A,2022,2022-10-22,Santos,0,1,Corinthians,VV,0,3,324,1743.20,1819.85,1717.77,1845.28
17132,Série A,2022,2022-10-26,Corinthians,0,2,Fluminense,VV,0,3,333,1845.28,1785.18,1811.95,1818.51
17146,Série A,2022,2022-10-29,Goiás,0,0,Corinthians,E,1,1,341,1734.19,1811.95,1732.66,1813.48
17152,Série A,2022,2022-11-02,Flamengo,1,2,Corinthians,VV,0,3,346,1918.25,1813.48,1879.65,1852.08
17161,Série A,2022,2022-11-05,Corinthians,1,0,Ceará,VC,3,0,354,1852.08,1623.62,1860.32,1615.38
17184,Série A,2022,2022-11-09,Coritiba,2,2,Corinthians,E,1,1,369,1697.71,1860.32,1702.73,1855.30
17192,Série A,2022,2022-11-13,Corinthians,0,1,Atlético-MG,VV,0,3,375,1855.30,1772.11,1819.46,1807.95
17266,CBR,2023,2023-04-12,Remo,2,0,Corinthians,VC,3,0,70,1525.67,1819.46,1565.51,1779.62
17290,Série A,2023,2023-04-16,Corinthians,2,1,Cruzeiro,VC,3,0,10,1779.62,1626.80,1790.08,1616.34
17308,Série A,2023,2023-04-23,Goiás,3,1,Corinthians,VC,3,0,16,1665.69,1790.08,1694.10,1761.67
17321,CBR,2023,2023-04-26,Corinthians,2,0,Remo,VC,3,0,84,1761.67,1565.51,1768.66,1558.52
17336,Série A,2023,2023-04-29,Palmeiras,2,1,Corinthians,VC,3,0,25,1925.36,1768.66,1935.70,1758.32
17375,Série A,2023,2023-05-08,Corinthians,1,1,Fortaleza,E,1,1,40,1758.32,1898.38,1761.42,1895.28
17387,Série A,2023,2023-05-11,Botafogo,3,0,Corinthians,VC,3,0,48,1841.81,1761.42,1854.61,1748.62
17404,Série A,2023,2023-05-14,Corinthians,1,1,São Paulo,E,1,1,56,1748.62,1822.48,1746.84,1824.26
17412,CBR,2023,2023-05-17,Atlético-MG,2,0,Corinthians,VC,3,0,99,1799.94,1746.84,1810.06,1736.72
17429,Série A,2023,2023-05-21,Flamengo,1,0,Corinthians,VC,3,0,68,1751.75,1736.72,1765.87,1722.60
17460,Série A,2023,2023-05-28,Corinthians,2,0,Fluminense,VC,3,0,77,1722.60,1878.57,1755.24,1845.93
17468,CBR,2023,2023-05-31,Corinthians,2,0,Atlético-MG,VC,3,0,101,1755.24,1831.86,1772.19,1814.91
17484,Série A,2023,2023-06-03,América-MG,2,0,Corinthians,VC,3,0,81,1702.64,1772.19,1724.33,1750.50
17508,Série A,2023,2023-06-10,Corinthians,1,1,Cuiabá,E,1,1,91,1750.50,1685.51,1740.22,1695.79
17528,Série A,2023,2023-06-21,Santos,0,2,Corinthians,VV,0,3,103,1719.07,1740.22,1692.99,1766.30
17540,Série A,2023,2023-06-24,Athletico-PR,1,0,Corinthians,VC,3,0,112,1750.04,1766.30,1765.93,1750.41
17581,Série A,2023,2023-07-02,Corinthians,0,1,Red Bull Bragantino,VV,0,3,128,1750.41,1757.27,1724.74,1782.94
17586,CBR,2023,2023-07-05,América-MG,1,0,Corinthians,VC,3,0,110,1697.79,1724.74,1710.48,1712.05
17592,Série A,2023,2023-07-08,Atlético-MG,0,1,Corinthians,VV,0,3,134,1799.30,1712.05,1762.95,1748.40
17616,CBR,2023,2023-07-15,Corinthians,3,2,América-MG,VC,3,0,116,1748.40,1684.62,1758.15,1674.87

In [ ]:
7